# Generated by Django 3.2.12 on 2022-04-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='orderitems',
        ),
    ]
