# Generated by Django 3.2.12 on 2022-04-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_resumen_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumen',
        ),
    ]
